import React from 'react';
import styles from '../../styles/pages/Demo/page.module.scss';
import {
    IcoGoogle,
    IcoNaver,
    IcoKakao,
    IcoDemo,
    IcoVisibleOn,
    IcoVisibleOnFill,
    IcoVisibleOff,
    IcoVisibleOffFill,
    IcoError,
    IcoCheck,
    IcoDelete,
    IcoSearch,
    IcoArrow,
    IcoArrowUp,
    IcoAnalytics,
    IcoBookmark,
    IcoCase,
    IcoDemography,
    IcoFinance,
    IcoInventory,
    IcoMail,
    IcoNet,
    IcoPeople,
    IcoSetting,
    IcoLogo,
    IcoNotification,
    IcoPerson,
    IcoFavorite,
    IcoFavoriteOn,
    IcoCol,
    IcoCheckbox,
    IcoDropdown,
    IcoLabel,
    IcoNumber,
    IcoSignature,
    IcoTextbox,
    IcoCalendar,
    IcoLink,
    IcoDepartment,
    IcoEmployee,
    IcoMultiline,
    IcoStamp,
    IcoAttachFile,
    IcoTemp,
    IcoClose,
    IcoInfo,
    IcoEmptyGrey,
    IcoEmptyBlue,
    IcoEmpty2Grey,
    IcoEmpty2Blue,
    IcoAdd,
    IcoGuide,
    IcoMinus,
    IcoShortInfo,
    IcoToastBasic,
    IcoToastError,
    IcoUpload,
    IcoExclamation,
    IcoTrash,
    IcoTrashFill,
    IcoFile,
    IcoDownload,
    IcoTakeBack,
    IcoBack,
    IcoPersonFill,
    IcoCoworker,
    IcoGroup,
    IcoGroup2,
    IcoDownEvaluation,
    IcoUpEvaluation,
    IcoEdit,
    IcoPreview,
    IcoLanguage,
    IcoFont,
    IcoPaint,
    IcoLogin,
    IcoArrowOutward,
    IcoCheckFill,
    IcoCopy,
    IcoProfile,
    IcoMobile,
    IcoUnlock,
    IcoLinkOff,
    IcoCompany,
    IcoCircle,
    IcoMaster,
    IcoArrowOutWard,
    IcoProfileStroke,
    IcoAddGroup,
    IcoFitScreen,
    IcoRedo,
    IcoUndo,
    IcoAddPerson,
    IcoChageFile,
    IcoIdentification,
    IcoAddress,
    IcoBirth,
    IcoMemberName,
    IcoRadio,
    IcoEditFill,
    IcoQuestionMark,
    IcoAlignBottom,
    IcoAlignCenter,
    IcoAlignLeft,
    IcoAlignMiddle,
    IcoAlignRight,
    IcoAlignTop,
    IcoHorizontalView,
    IcoVerticalView,
    IcoPersonCheck,
    IcoGroup3,
    IcoCardData,
    IcoCardCareer,
    IcoCardContact,
    IcoCardDisabled,
    IcoCardEducation,
    IcoCardFamily,
    IcoCardHistory,
    IcoCardHr,
    IcoCardLanguage,
    IcoCardMilitary,
    IcoCardPatriptism,
    IcoCardQualification,
    IcoCardReward,
    IcoCardTraining,
    IcoCardAppointment,
    IcoCamera,
    IcoPlus,
    IcoExpand,
    IcoCollapse,
    IcoArrowLeft,
} from '../../../public/asset/Icon';
const iconList = [
    { name: 'Google', component: <IcoGoogle /> },
    { name: 'Naver', component: <IcoNaver /> },
    { name: 'Kakao', component: <IcoKakao /> },
    { name: 'Demo', component: <IcoDemo /> },
    { name: 'VisibleOn', component: <IcoVisibleOn /> },
    { name: 'VisibleOnFill', component: <IcoVisibleOnFill /> },
    { name: 'VisibleOff', component: <IcoVisibleOff /> },
    { name: 'VisibleOffFill', component: <IcoVisibleOffFill /> },
    { name: 'Error', component: <IcoError /> },
    { name: 'Check', component: <IcoCheck /> },
    { name: 'Delete', component: <IcoDelete /> },
    { name: 'Search', component: <IcoSearch /> },
    { name: 'Arrow', component: <IcoArrow /> },
    { name: 'ArrowUp', component: <IcoArrowUp /> },
    { name: 'ArrowLeft', component: <IcoArrowLeft /> },
    { name: 'Analytics', component: <IcoAnalytics /> },
    { name: 'Bookmark', component: <IcoBookmark /> },
    { name: 'Case', component: <IcoCase /> },
    { name: 'Demography', component: <IcoDemography /> },
    { name: 'Finance', component: <IcoFinance /> },
    { name: 'Inventory', component: <IcoInventory /> },
    { name: 'Mail', component: <IcoMail /> },
    { name: 'Net', component: <IcoNet /> },
    { name: 'People', component: <IcoPeople /> },
    { name: 'Setting', component: <IcoSetting /> },
    { name: 'Logo', component: <IcoLogo /> },
    { name: 'Notification', component: <IcoNotification /> },
    { name: 'Person', component: <IcoPerson /> },
    { name: 'Favorite', component: <IcoFavorite /> },
    { name: 'FavoriteOn', component: <IcoFavoriteOn /> },
    { name: 'Col', component: <IcoCol /> },
    { name: 'Checkbox', component: <IcoCheckbox /> },
    { name: 'Dropdown', component: <IcoDropdown /> },
    { name: 'Label', component: <IcoLabel /> },
    { name: 'Number', component: <IcoNumber /> },
    { name: 'Signature', component: <IcoSignature /> },
    { name: 'Textbox', component: <IcoTextbox /> },
    { name: 'Calendar', component: <IcoCalendar /> },
    { name: 'Link', component: <IcoLink /> },
    { name: 'Department', component: <IcoDepartment /> },
    { name: 'Employee', component: <IcoEmployee /> },
    { name: 'Multiline', component: <IcoMultiline /> },
    { name: 'Stamp', component: <IcoStamp /> },
    { name: 'AttachFile', component: <IcoAttachFile /> },
    { name: 'Temp', component: <IcoTemp /> },
    { name: 'Close', component: <IcoClose /> },
    { name: 'Info', component: <IcoInfo /> },
    { name: 'EmptyGrey', component: <IcoEmptyGrey /> },
    { name: 'EmptyBlue', component: <IcoEmptyBlue /> },
    { name: 'Empty2Grey', component: <IcoEmpty2Grey /> },
    { name: 'Empty2Blue', component: <IcoEmpty2Blue /> },
    { name: 'Add', component: <IcoAdd /> },
    { name: 'Guide', component: <IcoGuide /> },
    { name: 'Minus', component: <IcoMinus /> },
    { name: 'ShortInfo', component: <IcoShortInfo /> },
    { name: 'ToastBasic', component: <IcoToastBasic /> },
    { name: 'ToastError', component: <IcoToastError /> },
    { name: 'Upload', component: <IcoUpload /> },
    { name: 'Exclamation', component: <IcoExclamation /> },
    { name: 'Trash', component: <IcoTrash /> },
    { name: 'TrashFill', component: <IcoTrashFill /> },
    { name: 'File', component: <IcoFile /> },
    { name: 'Download', component: <IcoDownload /> },
    { name: 'TakeBack', component: <IcoTakeBack /> },
    { name: 'Back', component: <IcoBack /> },
    { name: 'PersonFill', component: <IcoPersonFill /> },
    { name: 'Coworker', component: <IcoCoworker /> },
    { name: 'Group', component: <IcoGroup /> },
    { name: 'Group2', component: <IcoGroup2 /> },
    { name: 'Group3', component: <IcoGroup3 /> },
    { name: 'Down Evaluation', component: <IcoDownEvaluation /> },
    { name: 'Up Evaluation', component: <IcoUpEvaluation /> },
    { name: 'Edit', component: <IcoEdit /> },
    { name: 'Preview', component: <IcoPreview /> },
    { name: 'Language', component: <IcoLanguage /> },
    { name: 'Font', component: <IcoFont /> },
    { name: 'Paint', component: <IcoPaint /> },
    { name: 'Login', component: <IcoLogin /> },
    { name: 'CheckFill', component: <IcoCheckFill /> },
    { name: 'Copy', component: <IcoCopy /> },
    { name: 'Profile', component: <IcoProfile /> },
    { name: 'ProfileStroke', component: <IcoProfileStroke /> },
    { name: 'Mobile', component: <IcoMobile /> },
    { name: 'Unlock', component: <IcoUnlock /> },
    { name: 'LinkOff', component: <IcoLinkOff /> },
    { name: 'Company', component: <IcoCompany /> },
    { name: 'Circle', component: <IcoCircle /> },
    { name: 'Master', component: <IcoMaster /> },
    { name: 'ArrowOutWard', component: <IcoArrowOutWard /> },
    { name: 'FitScreen', component: <IcoFitScreen /> },
    { name: 'Undo', component: <IcoUndo /> },
    { name: 'Redo', component: <IcoRedo /> },
    { name: 'AddGroup', component: <IcoAddGroup /> },
    { name: 'AddPerson', component: <IcoAddPerson /> },
    { name: 'ChageFile', component: <IcoChageFile /> },
    { name: 'MemberName', component: <IcoMemberName /> },
    { name: 'Identification', component: <IcoIdentification /> },
    { name: 'Birth', component: <IcoBirth /> },
    { name: 'Address', component: <IcoAddress /> },
    { name: 'Radio', component: <IcoRadio /> },
    { name: 'EditFill', component: <IcoEditFill /> },
    { name: 'QuestionMark', component: <IcoQuestionMark /> },
    { name: 'AlignLeft', component: <IcoAlignLeft /> },
    { name: 'AlignCenter', component: <IcoAlignCenter /> },
    { name: 'AlignRight', component: <IcoAlignRight /> },
    { name: 'AlignTop', component: <IcoAlignTop /> },
    { name: 'AlignMiddle', component: <IcoAlignMiddle /> },
    { name: 'AlignBottom', component: <IcoAlignBottom /> },
    { name: 'HorizontalView', component: <IcoHorizontalView /> },
    { name: 'VerticalView', component: <IcoVerticalView /> },
    { name: 'PersonCheck', component: <IcoPersonCheck /> },
    { name: 'CardCareer', component: <IcoCardCareer /> },
    { name: 'CardContact', component: <IcoCardContact /> },
    { name: 'CardData', component: <IcoCardData /> },
    { name: 'CardDisabled', component: <IcoCardDisabled /> },
    { name: 'CardEducation', component: <IcoCardEducation /> },
    { name: 'CardFamily', component: <IcoCardFamily /> },
    { name: 'CardHistory', component: <IcoCardHistory /> },
    { name: 'CardHr', component: <IcoCardHr /> },
    { name: 'CardLanguage', component: <IcoCardLanguage /> },
    { name: 'CardMilitary', component: <IcoCardMilitary /> },
    { name: 'CardPatriptism', component: <IcoCardPatriptism /> },
    { name: 'CardQualification', component: <IcoCardQualification /> },
    { name: 'CardReward', component: <IcoCardReward /> },
    { name: 'CardTraining', component: <IcoCardTraining /> },
    { name: 'CardAppointment', component: <IcoCardAppointment /> },
    { name: 'Camera', component: <IcoCamera /> },
    { name: 'Plus', component: <IcoPlus /> },
    { name: 'Expand', component: <IcoExpand /> },
    { name: 'Collapse', component: <IcoCollapse /> },
];

const PreviewIcons = () => {
    return (
        <ul className={styles.previewIconList}>
            {iconList.map((icon, index) => (
                <li key={index} className={styles.item}>
                    <div className={styles.icon}>{icon.component}</div>
                    <div className={styles.name}>Ico{icon.name}</div>
                </li>
            ))}
        </ul>
    );
};

export default PreviewIcons;
